name: Deploy to EC2 for develop branch

on:
  push:
    branches: [ 'develop-v*.*.*' ]
  pull_request:
    branches: [ 'develop-v*.*.*' ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: development
    env:
      DATABASE_URL: ${{ vars.DATABASE_URL }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
    
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 10 
    
    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
    
    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    
    - name: Build
      run: pnpm prisma:migrate && pnpm prisma:generate && pnpm build
    
    # - name: Run tests
    #   run: pnpm test

    - name: Setup SSH key for appleboy/drone-ssh
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
    
    - name: Deploy to EC2
      if: startsWith(github.ref, 'refs/heads/develop-v')
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          mkdir -p /home/ubuntu/deploy/expatpassbe
          cd /home/ubuntu/deploy/expatpassbe
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git pull origin ${{ github.ref_name }}
          pnpm install --frozen-lockfile
          pnpm prisma:migrate
          pnpm prisma:generate
          pnpm build
          pm2 restart auth-service || pm2 start dist/main.js --name auth-service 